version: '3.8'

services:
  app:
    build: .
    container_name: silverstripe_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: silverstripe_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silverstripe
      MYSQL_USER: silverstripe_user
      MYSQL_PASSWORD: silverstripe_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: silverstripe_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
